# Ruff configuration file
line-length = 88
target-version = "py38"

[lint]
select = ["E", "F", "W", "I", "N", "UP", "YTT", "S", "BLE", "FBT", "B", "A", "COM", "C4", "DTZ", "T10", "EXE", "ISC", "ICN", "G", "INP", "PIE", "T20", "PYI", "PT", "Q", "RSE", "RET", "SLF", "SIM", "TID", "TCH", "ARG", "PTH", "ERA", "PD", "PGH", "PL", "TRY", "FLY", "NPY", "AIR", "PERF", "FURB", "LOG", "RUF"]
ignore = [
    "RUF002",  # 日本語ドキュメント文字列の全角括弧を許可
    "RUF003",  # 日本語コメントの全角括弧を許可
]

[format]
quote-style = "double"
indent-style = "space"