# Ruff configuration file
line-length = 88
target-version = "py38"

[lint]
# CI互換性のための戦略的ルールセット（lint/format競合解決）
select = [
    "E",    # エラー (重要)
    "F",    # Fatal (重要)
    "W",    # 警告 (重要)
    "I",    # インポート順序
    "B",    # バグリスク (重要)
    "UP",   # Python更新推奨
]
ignore = [
    "RUF002",  # 日本語ドキュメント文字列の全角括弧を許可
    "RUF003",  # 日本語コメントの全角括弧を許可
    # format競合回避のための追加除外
    "E501",    # 行長制限 (formatで処理)
    "W292",    # ファイル終端改行 (formatで処理)
    "W293",    # 空行の空白 (formatで処理)
    "W291",    # 行末空白 (formatで処理)
]

[format]
quote-style = "double"
indent-style = "space"