# ===== RUFF CONFIGURATION =====
# Comprehensive ruff configuration optimized for CI pipeline and modern Python development

##############################
# 1. グローバル設定 (トップレベル)
##############################

# Python 3.9 互換
target-version = "py39"

# PEP8 最大行長 (Black と合わせる)
line-length = 88

# 自動修正可能なルールをすべて有効 (必要に応じて絞り込む)
fixable = ["ALL"]

# チェック対象から除外するディレクトリ・ファイル
exclude = [
  "__pycache__",
  ".venv",
  "build",
  "dist",
  ".git"
]

# 不要な # noqa を警告
forbid-unnecessary-noqa = true

##############################
# 2. lint ルールの選択・除外
##############################
[lint]
# 適用するルール (Flake8, Bugbear, isort, pyupgrade など)
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes

    "I",    # isort (import order)

    "UP",   # pyupgrade (Python syntax modernization)

    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions

    "PIE",  # flake8-pie

    "T20",  # flake8-print

    "RUF",  # Ruff-specific rules
    "SIM"   # flake8-simplify
]

# プロジェクト事情で無視したいルール
ignore = [
    "E501",   # 長すぎる行は ruff format で補正
    "E203",   # フォーマッタ (Black) と衝突しやすい空白
    "B008",   # デフォルト引数内での関数呼び出し
    "PIE800", # 不要な spread operator
    "T201",   # 開発中は print を許容
    "T203",   # 開発中は pprint を許容
    "SIM108", # 三項演算子の自動提案を抑制
    "SIM117"  # dict.get の自動提案を抑制
]

##############################
# 3. per-file での無視設定
##############################
[per-file-ignores]
"__init__.py"      = ["F401"]
"tests/**/*.py"    = ["T201", "T203", "B011", "SIM117"]
"conf.py"          = ["E402"]
"conftest.py"      = ["E402"]
"examples/**/*.py" = ["T201", "T203", "B008"]

##############################
# 4. フォーマット関連設定 (トップレベル)
##############################
# ダブルクォートを使う
quote-style = "double"

# 複数行での末尾カンマを保持する
skip-magic-trailing-comma = false

# インデントはスペース
indent-style = "space"

# 改行コードは自動判定 (lf/crlf を自動で選択)
line-ending = "auto"

# docstring 内の code block をフォーマット
docstring-code-format = true

# docstring 内のコード行長を動的に決定
docstring-code-line-length = "dynamic"
