"""Optimization package for performance improvements.

This package contains optimized components for various performance
bottlenecks identified in the sphinxcontrib-jsontable processing pipeline.
"""

from .duplicate_detector_optimized import (
    DuplicateDetectionResult,
    DuplicateDetectorOptimized,
    HashTableMetrics,
    OptimizationMetrics,
)
from .optimized_concurrent_processor import (
    AsyncProcessingMetrics,
    AsyncProcessingResult,
    ConcurrentBenchmarkResult,
    ConcurrentPerformanceMetrics,
    ConcurrentProcessingResult,
    OptimizedConcurrentProcessor,
    ResourceContentionMetrics,
    ResourceContentionResult,
    ScalabilityMetrics,
    ScalabilityResult,
    ThreadSafetyMetrics,
    ThreadSafetyResult,
)
from .optimized_header_processor import (
    BenchmarkComparisonResult,
    DuplicationEliminationMetrics,
    HeaderProcessingResult,
    LinearScalabilityTestResult,
    MemoryOptimizationResult,
    OptimizedHeaderProcessor,
    SinglePassHeaderResult,
)
from .optimized_index_processor import (
    CompositeIndexResult,
    ConcurrentIndexResult,
    HashIndexResult,
    IndexBenchmarkResult,
    IndexCacheMetrics,
    IndexOptimizationMetrics,
    IndexPerformanceMetrics,
    IndexProcessingResult,
    OptimizedIndexProcessor,
    RangeIndexResult,
)
from .optimized_security_scanner import (
    BenchmarkComparisonResult,
    ConcurrentSecurityResult,
    OptimizedSecurityScanner,
    SecurityOptimizationMetrics,
    SecurityPerformanceMetrics,
    SecurityScanResult,
    ThreatCacheMetrics,
    ThreatDetectionResult,
)
from .optimized_string_processor import (
    ConcurrentStringResult,
    OptimizedStringProcessor,
    RegexOptimizationResult,
    StringBenchmarkResult,
    StringCacheMetrics,
    StringMemoryMetrics,
    StringOptimizationMetrics,
    StringPerformanceMetrics,
    StringProcessingResult,
)
from .range_parser_optimized import (
    CacheMetrics,
    PerformanceMetrics,
    RangeParserOptimized,
    RangeParsingResult,
    RegexOptimizationMetrics,
)
from .unified_data_validator import (
    DataValidationMetrics,
    SecurityValidationMetrics,
    UnifiedDataValidator,
    UnifiedValidationResult,
    ValidationEfficiencyMetrics,
    ValidationIntegrationMetrics,
    ValidationPerformanceMetrics,
    ValidationQualityMetrics,
)

__all__ = [
    "OptimizedHeaderProcessor",
    "HeaderProcessingResult",
    "DuplicationEliminationMetrics",
    "SinglePassHeaderResult",
    "MemoryOptimizationResult",
    "BenchmarkComparisonResult",
    "LinearScalabilityTestResult",
    "DuplicateDetectorOptimized",
    "DuplicateDetectionResult",
    "HashTableMetrics",
    "OptimizationMetrics",
    "RangeParserOptimized",
    "RangeParsingResult",
    "CacheMetrics",
    "RegexOptimizationMetrics",
    "PerformanceMetrics",
    "UnifiedDataValidator",
    "UnifiedValidationResult",
    "DataValidationMetrics",
    "SecurityValidationMetrics",
    "ValidationIntegrationMetrics",
    "ValidationPerformanceMetrics",
    "ValidationQualityMetrics",
    "ValidationEfficiencyMetrics",
    "OptimizedSecurityScanner",
    "SecurityScanResult",
    "ThreatDetectionResult",
    "SecurityOptimizationMetrics",
    "SecurityPerformanceMetrics",
    "ThreatCacheMetrics",
    "ConcurrentSecurityResult",
    "OptimizedStringProcessor",
    "StringProcessingResult",
    "StringOptimizationMetrics",
    "StringPerformanceMetrics",
    "RegexOptimizationResult",
    "StringCacheMetrics",
    "ConcurrentStringResult",
    "StringMemoryMetrics",
    "StringBenchmarkResult",
    "OptimizedIndexProcessor",
    "IndexProcessingResult",
    "IndexOptimizationMetrics",
    "IndexPerformanceMetrics",
    "HashIndexResult",
    "RangeIndexResult",
    "CompositeIndexResult",
    "ConcurrentIndexResult",
    "IndexCacheMetrics",
    "IndexBenchmarkResult",
    "OptimizedConcurrentProcessor",
    "ConcurrentProcessingResult",
    "AsyncProcessingResult",
    "ThreadSafetyResult",
    "ResourceContentionResult",
    "ScalabilityResult",
    "ConcurrentBenchmarkResult",
    "ConcurrentPerformanceMetrics",
    "AsyncProcessingMetrics",
    "ThreadSafetyMetrics",
    "ResourceContentionMetrics",
    "ScalabilityMetrics",
]
